In [22]:
import pandas as pd
import numpy as np
from datasets import load_dataset
import matplotlib.pyplot as plt

# loading data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

Index Management

In [23]:
df.sample(2)
# indx has no name

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
264036,Data Engineer,"Principal, Data Engineer","Westlake, TX",via Dice.com,Full-time,False,"Florida, United States",2023-07-17 07:17:44,False,False,United States,NaN,NaN,NaN,Fidelity Investments,"['python', 'scala', 'java', 'nosql', 'mongodb'...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
442826,Data Engineer,Data Engineer,United Kingdom,via Big Country Jobs,Contractor,False,United Kingdom,2023-01-04 01:43:37,True,False,United Kingdom,NaN,NaN,NaN,Outsource UK,"['sql', 'python', 'pyspark']","{'libraries': ['pyspark'], 'programming': ['sq..."

In [24]:
df.index

RangeIndex(start=0, stop=785741, step=1)

In [ ]:
# giving indx column a name
df.index.name = 'job_index'
#df.sort_values('job_index', ascending=False) this method does not work, though we gave the index column a name, still can not 
# sort it using sortvalues and must use sort_index for this column
df.sort_index(ascending=False)
df.sample(2)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
699782,Data Analyst,Vendor Data Analyst,Anywhere,via Snagajob,Full-time and Part-time,True,"Texas, United States",2023-12-17 03:00:44,False,True,United States,hour,NaN,16.51,The University of Texas at Dallas,NaN,NaN
638182,Data Scientist,Head of Data Science and Analytics,"San Francisco, CA",via Ladders,Full-time,False,"California, United States",2023-08-21 12:05:38,False,True,United States,year,350000.0,NaN,Nextdoor,"['python', 'r', 'sql', 'hadoop', 'spark']","{'libraries': ['hadoop', 'spark'], 'programmin..."

In [26]:
print(df.index.dtype)

df['job_title_short'].dtype

int64

Index Reset

In [32]:
df_usa = df.loc[df['job_country']=='United States',['job_title_short','job_country']]
#indices are missing some values as a filter is applied
df_usa

                job_title_short    job_country
job_index
0          Senior Data Engineer  United States
3                 Data Engineer  United States
5                 Data Engineer  United States
6          Senior Data Engineer  United States
9                Data Scientist  United States
...                         ...            ...
785673           Data Scientist  United States
785685             Data Analyst  United States
785692           Data Scientist  United States
785703             Data Analyst  United States
785705             Data Analyst  United States

[206292 rows x 2 columns]

Index Reset

In [49]:
df_usa.reset_index(inplace=True)
df_usa
#each time this code is run, a new index column is added, try and run this code again

        job_index  level_0   index       job_title_short    job_country
0               0        0       0  Senior Data Engineer  United States
1               3        1       1         Data Engineer  United States
2               5        2       2         Data Engineer  United States
3               6        3       3  Senior Data Engineer  United States
4               9        4       4        Data Scientist  United States
...           ...      ...     ...                   ...            ...
206287     785673   206287  206287        Data Scientist  United States
206288     785685   206288  206288          Data Analyst  United States
206289     785692   206289  206289        Data Scientist  United States
206290     785703   206290  206290          Data Analyst  United States
206291     785705   206291  206291          Data Analyst  United States

[206292 rows x 5 columns]

Set INDEX

In [ ]:
df_usa.set_index('job_index', inplace=True)
# gives error if run another time, saying 'job_index' does not exist

KeyError: "None of ['job_index'] are in the columns"

In [47]:
df_usa

           level_0   index       job_title_short    job_country
job_index
0                0       0  Senior Data Engineer  United States
3                1       1         Data Engineer  United States
5                2       2         Data Engineer  United States
6                3       3  Senior Data Engineer  United States
9                4       4        Data Scientist  United States
...            ...     ...                   ...            ...
785673      206287  206287        Data Scientist  United States
785685      206288  206288          Data Analyst  United States
785692      206289  206289        Data Scientist  United States
785703      206290  206290          Data Analyst  United States
785705      206291  206291          Data Analyst  United States

[206292 rows x 4 columns]